/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    val farewell: String
        get() {
            return "Goodbye World!"
        }
}

fun main() {
    val app = App()

    val pair = Pair<String, String>(app.greeting, app.farewell)

    println(pair.first)
    println(pair.second)
}
